// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDusDOx8joVZ9xcuNBqIMe0WQjqrqKdII0',
    appId: '1:526710490917:web:b364d56a1e97806eebfccc',
    messagingSenderId: '526710490917',
    projectId: 'k31-watch',
    authDomain: 'k31-watch.firebaseapp.com',
    storageBucket: 'k31-watch.appspot.com',
    measurementId: 'G-YK3L331R8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdYd35WMWEK-kxOU4BnuGN6k-RW2w9moI',
    appId: '1:526710490917:android:426526dced00d57febfccc',
    messagingSenderId: '526710490917',
    projectId: 'k31-watch',
    storageBucket: 'k31-watch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8XMPIYVMVGaI6QxPMYYIYWFhjf9o5W5o',
    appId: '1:526710490917:ios:6049d6bc6aae6604ebfccc',
    messagingSenderId: '526710490917',
    projectId: 'k31-watch',
    storageBucket: 'k31-watch.appspot.com',
    iosBundleId: 'com.example.k31WatchFlutter',
  );
}
